# Generated by Django 5.2.4 on 2025-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='tovar nomi')),
                ('description', models.TextField(verbose_name='tovar haqida')),
                ('price', models.IntegerField(verbose_name='tovar narxi')),
                ('discount_precent', models.PositiveSmallIntegerField(verbose_name='chegirma foizi')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
